include config


all:
	cd zerofps/; $(MAKE) $@
	cd common/; $(MAKE) $@
	cd zeroedit/; $(MAKE) $@	
	cd zerorts/; $(MAKE) $@	
	
clean:
	cd zerofps/; $(MAKE) $@
	cd common/; $(MAKE) $@
	cd zeroedit/; $(MAKE) $@	
	cd zerorts/; $(MAKE) $@	
	