include ../config


all:
	cd basic/; $(MAKE) $@
	cd gui/; $(MAKE) $@	
	cd physics_engine/; $(MAKE) $@	
	cd render/; $(MAKE) $@	
	cd engine_systems/; $(MAKE) $@	
	cd engine/; $(MAKE) $@	
	
clean:
	cd basic/; $(MAKE) $@
	cd gui/; $(MAKE) $@	
	cd physics_engine/; $(MAKE) $@	
	cd render/; $(MAKE) $@	
	cd engine_systems/; $(MAKE) $@	
	cd engine/; $(MAKE) $@	
	