//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by zguied.rc
//
#define IDD_DIALOGLEFT                  102
#define IDD_DIALOGBOTTOM                103
#define IDD_SELECTFONT_DLGBOX           104
#define IDD_SELECTSCRIPT                105
#define IDI_ICON1                       106
#define IDD_SELECTFONT                  107
#define IDC_WINDOW_NAMEID_EB            1002
#define IDC_TEXTLABEL_EB                1003
#define IDC_NEWCNTRL_CB                 1004
#define IDC_WINDOW_NAMEID_EB2           1005
#define IDC_PARENT_WINDOW_NAMEID        1006
#define IDC_CREATE_WND_BN               1007
#define IDC_PARENT_WINDOW_NAMEID2       1008
#define IDC_WINDOWTYPE_EB               1009
#define IDC_RESIZE_WND                  1010
#define IDC_LOADGUI                     1011
#define IDC_POSX_EB                     1012
#define IDC_RESIZE_WND2                 1013
#define IDC_FORCE_CAPTURE_TO_SEL_CB     1014
#define IDC_SAVE                        1015
#define IDC_SAVE_SCRIPT                 1016
#define IDC_WIDTH_EB                    1017
#define IDC_DELETE_WND_BN               1018
#define IDC_POSY_EB                     1019
#define IDC_NEWGUI_BN                   1020
#define IDC_EDIT4                       1021
#define IDC_TESTGUI_BN                  1022
#define IDC_HEIGHT_EB                   1023
#define IDC_FILELIST_CB                 1024
#define IDC_LIST3                       1025
#define IDC_WINDOW_LIST                 1026
#define IDC_DISABLE_MOVE_CB             1027
#define IDC_WINDOW_LIST3                1028
#define IDC_SELECT_SCRIPT_FOLDER_LIST   1029
#define IDC_TILE_CB                     1030
#define IDC_WINDOW_LIST2                1031
#define IDC_TRANSPARENT_CB              1032
#define IDC_TEXTURE_LIST                1033
#define IDC_VISIBLE_CHECK               1034
#define IDC_ONLY_OF_WND_TYPE_CB         1035
#define IDC_BUTTON1                     1036
#define IDC_PICK_COLOR_BN               1036
#define IDC_COPY_WND_BN                 1037
#define IDC_SELECTFONT_OK_BN            1038
#define IDC_BRING_TO_FRONT              1039
#define IDC_SELECTFONT_CANCEL_BN        1040
#define IDC_PASTE_WND_BN                1041
#define IDC_LIST1                       1042
#define IDC_FONT_LIST                   1043
#define IDC_BRING_TO_FRONT2             1044
#define IDC_                            1045
#define IDC_SET_TEXTURE_BN              1046
#define IDC_SKINELEMENTS_LIST           1047
#define IDC_BRING_TO_FRONT3             1048
#define IDC_REMOVE_TEXTURE_BN           1049
#define IDC_SKINTYPE_BACKGROUND_RB      1050
#define IDC_REMOVE_TEXTURE_BN2          1051
#define IDC_RESIZE_TO_IMAGE             1052
#define IDC_SKINTYPE_HORZBORDER_RB      1053
#define IDC_SKINTYPE_VERTBORDER_RB      1054
#define IDC_RADIO4                      1055
#define IDC_SKINTYPE_CORNERBORDER_RB    1056
#define IDC_BORDER_EB                   1057
#define IDC_ROTATION_EB                 1058
#define IDC_FREE_MOVEMENT_CB            1059
#define IDC_HIDDEN_FROM_START_CB        1060
#define IDC_SELECTFONT_BN               1061
#define IDC_RGB_COLOR_R_EB              1062
#define IDC_PASTE_SKIN                  1063
#define IDC_OPEN_SPECIAL_ATTIBUTES_BN   1064
#define IDC_RGB_COLOR_G_EB              1065
#define IDC_RGB_COLOR_B_EB              1066
#define IDC_FONT_COLOR_R_EB             1067
#define IDC_ZVALUE_EB                   1068
#define IDC_FONT_COLOR_G_EB             1069
#define IDC_FONT_COLOR_B_EB             1070
#define IDC_COPY_SKIN                   1071
#define IDC_COPY_ALL_SKINS              1072
#define IDC_CHECK1                      1073
#define IDC_ACTIVATE_HELP_CB            1074
#define IDC_RADIO6                      1075
#define IDC_RADIO7                      1076
#define IDC_RADIO8                      1077
#define IDC_RADIO9                      1078
#define IDC_SHOW_KEYS_BN                1079
#define IDC_CLOSE_BUTTON                1080
#define IDC_WNDALIGNMENT_TOPLEFT        1081
#define IDC_CLOSE_BUTTON2               1081
#define IDC_WNDALIGNMENT_CENTERVERT     1082
#define IDC_WNDALIGNMENT_TOPRIGHT       1083
#define IDC_WNDALIGNMENT_CENTER         1084
#define IDC_WNDALIGNMENT_BOTTOMLEFT     1085
#define IDC_WNDALIGNMENT_CENTERHORZ     1086
#define IDC_WNDALIGNMENT_BOTTOMRIGHT    1087
#define IDC_RESIZETYPE_DONT             1088
#define IDC_RESIZETYPE_HEIGHT           1089
#define IDC_RESIZETYPE_WIDTH            1090
#define IDC_RESIZETYPE_BOTH             1091
#define IDC_MINIMIZE_BUTTON             1092
#define IDC_IMAGE_INFO_LABEL            1093
#define IDC_MULTILINE_CB                1094
#define IDC_SCREEN_ALIGNMENT_GB         1095
#define IDC_HORIZONTAL_CB               1096
#define IDC_PROGRESSBAR_DIR1_RB         1097
#define IDC_PROGRESSBAR_DIR2_RB         1098
#define IDC_PROGRESSBAR_DIR3_RB         1099
#define IDC_PROGRESSBAR_DIR4_RB         1100
#define IDC_PROGRESSBAR_DIR_GROUP_LABEL 1101
#define IDC_PROGRESSBAR_TEXTORIENT_GROUP_LABEL 1102
#define IDC_PBTEXTORIENT_RB1            1103
#define IDC_PBTEXTORIENT_RB2            1104
#define IDC_PBTEXTORIENT_RB3            1105
#define IDC_PBTEXTORIENT_RB4            1106
#define IDC_PBTEXTORIENT_RB5            1107
#define IDC_PBTEXTORIENT_RB6            1108
#define IDC_SELECTSCRIPT_CANCEL         1109
#define IDC_SELECTSCRIPT_OK             1110
#define IDC_SELECTFILE_LIST             1111
#define IDC_SELEC_SCRIPT_LABEL          1112
#define IDC_SAVEFILE_NAME_EB            1113
#define IDC_EDIT1                       1114
#define IDC_CURRENT_PATH_EB             1114
#define ID_SDSD_DSFSD                   40001
#define ID_SDFSDF_SDF                   40002
#define ID_SDF_SDF                      40003
#define ID_SDF_DDD                      40004
#define ID_DDSFS_SDSD                   40005
#define ID_SDFSDF_DSF                   40007
#define ID_S_SDF                        40008
#define ID_CREATENEW_WINDOW             40011
#define ID_CREATENEW_BUTTON             40012
#define ID_CREATENEW_CHECKBOX           40013
#define ID_CREATENEW_COMBOBOX           40014
#define ID_CREATENEW_LISTBOX            40015
#define ID_CREATENEW_RADIOBUTTON        40016
#define ID_CREATENEW_TABCONTROLL        40017
#define ID_CREATENEW_PROGRESSBAR        40018
#define ID_QUITAPP                      40019
#define ID_CREATE_SET                   40020
#define ID_SET_WINDOWNAME               40021

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        106
#define _APS_NEXT_COMMAND_VALUE         40022
#define _APS_NEXT_CONTROL_VALUE         1115
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
