
#ifndef RES_ID
#define RES_ID

enum WindowResID
{
	ID_MAINWND_MENU=1,
	ID_CLOSE=883,
	ID_OPEN_TEMPLATE=884,
	ID_LOAD_MAP=885,
	IDM_CLOSE=886,
	IDM_OPEN=887,
	IDM_MENU_WND,
	IDM_CREATE_NEW_PROPERTY=888,
/*	ID_PROPERTY_WND,
	ID_PROPERTY_WND_MAIN,
	ID_PROPERTY_WND_CLOSE,
	ID_NAME_TEXTBOX,
	ID_POSX_TEXTBOX,
	ID_POSY_TEXTBOX,
	ID_POSZ_TEXTBOX,
	ID_OBJECTS_CB,
	ID_PROPERTIES_CB,*/
	ID_BITMAP_FONT,
/*	ID_PROPERTY_OK,
	ID_PROPERTY_CANCEL,*/
	IDM_LOAD_HEIGHTMAP,
	ID_MAINWND_MENU_CB,
	ID_ADDPROPERTY_BN,
	ID_ADDPROPERTY_WND,
	ID_ADDPROPERTY_CLOSE,
	ID_ADDPROPERTY_OK,
/*	ID_REMOVEPROPERTY_BN,
	ID_PROPERTY_VALUES_CB,
	ID_PROPERTY_NEW_VALUE_EB,
	ID_PROPERTY_SET_NEW_VALUE_BN,*/
	IDM_LOAD_TEMPLATE,
	IDM_SAVE_TEMPLATE,
	ID_ADDPROPERTY_WND_MAIN,
	ID_WORKPANEL,
	ID_WORKPANEL_MAINWND,
	ID_AUTOSMOOTHGROUND_CHB,
	ID_MADOBJECTS_LB,
	ID_LOADMADFILE,
	ID_TEXCOLOR_RED_EB,
	ID_TEXCOLOR_GREEN_EB,
	ID_TEXCOLOR_BLUE_EB,
	ID_TERRAINTEXTURE_CB,

	ID_OBJECTTYPE_RADIOGROUP	 = 10000, 
	ID_PROPERTY_RADIOGROUP		 = 10100, 
	ID_BRUSHSIZE_RADIOGROUP		 = 10200,
	ID_PENCILSIZE_RADIOGROUP	 = 10300,
	ID_ELEVATIONMODE_RADIOGROUP  = 10400,
};
 
#endif
