#ifndef _ZGRESOURCE_ID_H
#define _ZGRESOURCE_ID_H

enum WindowIDs
{
	ID_CTRLBOX_WND=1,
	ID_CTRLBOX_MAIN_WND,
	ID_CTRLPROPERTYBOX_MAIN_WND,
	ID_CTRLPROPERTYBOX_WND,
	ID_CTRL_WINDOW_BN,
	ID_CTRL_LABEL_BN,
	ID_CTRL_TEXTBOX_BN,
	ID_CTRL_BUTTON_BN,
	ID_CTRL_CHECKBOX_BN,
	ID_CTRL_RADIOBUTTON_BN,
	ID_CTRL_COMOBOBOX_BN,
	ID_CTRL_LISTBOX_BN,
	ID_CTRL_SCROLLBAR_BN,
	ID_CTRLID_EB,
	ID_CTRLCAPTION_EB,
	ID_CTRLOK_BN,
	ID_CTRLCANCEL_BN,
	ID_CTRLCLOSE_BN,
	ID_CTRLBOX_OPENSKINDLG_BN,
	ID_CTRLBOX_COPY_BN,
	ID_SKINBOX_WND,
	ID_SKINBOX_MAIN_WND,
	ID_SKINBOX_CLOSE_BN,
	ID_SKINBOX_OK_BN,
	ID_SKINBOX_TEXTURELIST_LB,
	ID_SKINBORDERSIZE_EB,
	ID_SKINTILEBORDER_CHB,
	ID_SKINBKREDCOLOR_SB,
	ID_SKINBKGREENCOLOR_SB,
	ID_SKINBKBLUECOLOR_SB,
	ID_SKINBORDERREDCOLOR_SB,
	ID_SKINBORDERGREENCOLOR_SB,
	ID_SKINBORDERBLUECOLOR_SB,
	ID_SKINBKREDCOLOR_EB,
	ID_SKINBKGREENCOLOR_EB,
	ID_SKINBKBLUECOLOR_EB,
	ID_SKINBORDERREDCOLOR_EB,
	ID_SKINBORDERGREENCOLOR_EB,
	ID_SKINBORDERBLUECOLOR_EB,
	ID_SKINBOX_CANCEL_BN,
	ID_SKINDLGTYPES_CB,
	ID_SKINTEXTURE_CHB,
	ID_CTRLTABORDERNR_EB,
	ID_GRID_CB,
	ID_GRID_PRECISION,
	ID_CTRLNAME_EB,
	ID_TRANSPARENTBK_CHB,
	ID_CRTLVERTHORZSCROLLBAR_CB,
	ID_CRTLMENUNORMAL_CB,
	ID_CRTLMULTILINETEXTBOX_CB,
	ID_CTRLNUMVISROWSCOMBOBOX_LAB,
	ID_CTRLNUMVISROWSCOMBOBOX_EB,
	ID_CTRLGROUPIDRADIOBN_EB,
	ID_CTRLGROUPIDRADIOBN_LAB,
	ID_CRTLMOVEABLEWND_CB,
	ID_CTRLPOSX_EB,
	ID_CTRLPOSY_EB,
	ID_CTRLWIDTH_EB,
	ID_CTRLHEIGHT_EB,
	ID_CRTLDISABLED_CB,
	ID_MENU_MAINWND,
	ID_MENU_WND,
	ID_FILE_MENU,
	IDM_NEW,
	IDM_OPENFILE,
	IDM_SAVEFILE,
	IDM_SAVEFILE_AS,
	IDM_EXIT,

	ID_SKINTEXTURETYPE_RB,
	LAST_ID, // måste vara sist fast inte efter radiogroup id'na...

	CTRLMENU_RADIO_GROUP			= 1000,
	ID_SKINTEXTURETYPE_GROUP		= 1050,

};


#endif // #ifndef _ZGRESOURCE_ID_H




