include config


all:
	cd zerofpsv2/; $(MAKE) $@
	cd mcommon/; $(MAKE) $@
#	cd mistclient/; $(MAKE) $@
	cd mistclient2/; $(MAKE) $@
	cd mistserver/; $(MAKE) $@
#	cd dark_metropolis/; $(MAKE) $@
#	cd dm_arcad/; $(MAKE) $@
#	cd zgresedit; $(MAKE) $@
	cd zeroed/; $(MAKE) $@
	cd stopemup/; $(MAKE) $@
	cd tools/tool/madview/; $(MAKE) $@
	cd tools/tool/zguiresed/; $(MAKE) $@
	cd tools/tool/zfmaster/; $(MAKE) $@	
	cd tools/tool/madmake/; $(MAKE) $@

	cd plugin/zfpmlserver/; $(MAKE) $@
	cd plugin/model/; $(MAKE) $@
	
	
	./gengdbinit.sh



clean:
	cd zerofpsv2/; $(MAKE) $@
	cd mcommon/; $(MAKE) $@
#	cd mistclient/; $(MAKE) $@
	cd mistclient2/; $(MAKE) $@
	cd mistserver/; $(MAKE) $@
#	cd dark_metropolis/; $(MAKE) $@
#	cd dm_arcad/; $(MAKE) $@
#	cd zgresedit/; $(MAKE) $@	
	cd zeroed/; $(MAKE) $@
	cd stopemup/; $(MAKE) $@
	cd tools/tool/madview/; $(MAKE) $@
	cd tools/tool/zguiresed/; $(MAKE) $@
	cd tools/tool/zfmaster/; $(MAKE) $@	
	cd tools/tool/madmake/; $(MAKE) $@
	
	cd plugin/zfpmlserver/; $(MAKE) $@
	cd plugin/model/; $(MAKE) $@
	
clean_engine:
	cd zerofpsv2/; $(MAKE) clean	

clean_apps:
	cd mcommon/; $(MAKE) clean
	cd zeroed/; $(MAKE) clean
	cd mistserver/; $(MAKE) clean
	cd mistclient2/; $(MAKE) clean
	cd tools/tool/madview/; $(MAKE) clean	
	cd stopemup/; $(MAKE) clean
	cd tools/tool/zfmaster/; $(MAKE) $@	
	cd tools/tool/madmake/; $(MAKE) $@		
	
