include config


all:
	cd zerofpsv2/; $(MAKE) $@
	cd mcommon/; $(MAKE) $@
	cd mistclient/; $(MAKE) $@
	cd mistserver/; $(MAKE) $@
	cd dark_metropolis/; $(MAKE) $@
	cd physics/; $(MAKE) $@
	
clean:
	cd zerofpsv2/; $(MAKE) $@
	cd mcommon/; $(MAKE) $@
	cd mistclient/; $(MAKE) $@
	cd mistserver/; $(MAKE) $@
	cd dark_metropolis/; $(MAKE) $@
	cd physics/; $(MAKE) $@

